export {default as Login} from './Login';
export {default as Register} from './Register';
export {default as Find} from './Find_ID';
export {default as Pass} from './Find_pass';
export {default as Join} from './Join';
export {default as Main} from './Main';
export {default as Major} from './Major';
export {default as Free} from './free';
export {default as Floor} from './floor';
export {default as one} from '../Components/location/onefloor';
export { default as two } from '../Components/location/twofloor';
export { default as three } from '../Components/location/threefloor';
export { default as four } from '../Components/location/fourfloor';